update workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -6,6 +6,7 @@ on:
     inputs:
       tag:
         description: "Tag / Version number"
+        required: true
       is-dry-run:
         description: "Dry-run (do not publish, only test build)"
         type: boolean
@@ -26,7 +27,10 @@ jobs:
     steps:
       - name: Check input tag format
         run: |
-          echo "${{ inputs.tag }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
+          if ! echo "${{ inputs.tag }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
+            echo "::error title=Invalid package version number::Version numbers must follow the Major.Minor.Patch format (e.g. 1.45.320)."
+            exit 1
+          fi
 
       - name: Checkout files
         uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
@@ -50,7 +54,7 @@ jobs:
           tcli build
           ARTIFACT_NAME=$(find "${{ env.build-dir }}" -type f -printf "%f\n")
           echo "artifact-name=${ARTIFACT_NAME}" >> "$GITHUB_ENV"
-          echo "artifact-path=${{ env.build-dir }}/${{ env.artifact-name }}" >> "$GITHUB_ENV"
+          echo "artifact-path=${{ env.build-dir }}/${ARTIFACT_NAME}" >> "$GITHUB_ENV"
 
       - name: Upload artifact to workflow
         uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
@@ -58,6 +62,12 @@ jobs:
           name: ${{ env.artifact-name }}
           path: ${{ env.artifact-path }}
           retention-days: 1
+
+      - name: Publish package
+        if: ${{ !inputs.is-dry-run }}
+        env:
+          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
+        run: tcli publish --file ${{ env.artifact-path }}
 
       - name: Tag and push to repository
         if: ${{ !inputs.is-dry-run }}
@@ -68,12 +78,6 @@ jobs:
           git commit --message "Release ${{ inputs.tag }}"
           git tag ${{ inputs.tag }}
           git push origin HEAD:${{ github.ref_name }} --tags
-
-      - name: Publish package
-        if: ${{ !inputs.is-dry-run }}
-        env:
-          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
-        run: tcli publish --file ${{ env.artifact-path }}
 
       - name: Create release
         id: release
